title: "Jeevan MR Blog"
name: "Jeevan MR"
description: "Thoughts on engineering, code, and learning."

# Production site URL. If you set a custom domain, update this to https://blog.jeevanmr.com
url: "https://jee1mr.github.io"
baseurl: ""
repository: "jee1mr/jee1mr.github.io"

# Minimal Mistakes via GitHub remote theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # Try: default, air, aqua, contrast, dark, dirt, neon, plum

# GitHub Pages-supported plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name: "Jeevan MR"
  bio: "Engineer. Tinkerer."
  location: "🌏"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jee1mr"
    # - label: "X"
    #   icon: "fab fa-fw fa-x-twitter"
    #   url: "https://x.com/<your-handle>"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jee1mr"

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tmp
  - README.md


